# This is a basic workflow to build a FHIR-IG and deplay the output to the gh-pages branch
# and publish on Git Hub Pages everytime it is pushed to the main branch
# set up GitHub Page to publish from the "gh-pages" branch like this:
# https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site#publishing-from-a-branch

name: Build and Deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: write
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3
      - name: FHIR IG Action   # action from the GitHub Marketplace
        # uses: Healthedata1/fhir-ig-action@v0.3.0-alpha
        uses: qligier/fhir-ig-action@feature_memory_debug
        with:
          java-flags: "-Xmx4G"
          sushi: "3.2.0"
        
      - name: Deploy to GitHub Pages  # action from the GitHub Marketplace
        uses: JamesIves/github-pages-deploy-action@v4.4.3
        with:
          folder: output # deploy from the prior step
